# Generated by Django 6.0.4 on 2026-05-09 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_checkout_deactivated_by_checkout_is_deactivated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersummary',
            name='checkout',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='checkout.checkout'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordersummary',
            name='notes',
            field=models.TextField(blank=True, help_text='Special instructions from the customer.', null=True),
        ),
        migrations.AddField(
            model_name='ordersummary',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ordersummary',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='checkout',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='checkout.checkout'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='is_successful',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='provider',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('cod', 'Cash on Delivery')], default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Stripe/PayPal intent ID', max_length=150, null=True),
        ),
    ]
