# Generated by Django 6.0.4 on 2026-05-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_ordersummary_checkout_ordersummary_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='user',
        ),
        migrations.AddField(
            model_name='checkout',
            name='session_key',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
