# Generated by Django 6.0.4 on 2026-04-29 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='color',
            field=models.CharField(blank=True, help_text='Color attribute.', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='dimensions',
            field=models.CharField(blank=True, help_text='Dimensions attribute.', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='fabric',
            field=models.CharField(blank=True, help_text='Fabric attribute.', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='size',
            field=models.CharField(blank=True, help_text='Size attribute.', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(blank=True, help_text='Unique SKU for the variant.', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='weight',
            field=models.CharField(blank=True, help_text='Weight attribute.', max_length=250, null=True),
        ),
    ]
