# Generated by Django 6.0.4 on 2026-04-25 16:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_disabled', models.BooleanField(default=False)),
                ('session_key', models.CharField(db_index=True, help_text="The user's session key whose preferences are being tracked.", max_length=100)),
                ('ordered_at', models.DateTimeField(auto_now_add=True, help_text='The timestamp when the purchase was made.')),
                ('total_spent', models.DecimalField(decimal_places=2, editable=False, help_text='The total cost of the purchase (price * quantity).', max_digits=12)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(help_text='The product that was purchased.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_by', to='order.order', verbose_name='orders')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_disabled', models.BooleanField(default=False)),
                ('session_key', models.CharField(help_text="Unique identifier for the guest's session.", max_length=255, unique=True)),
                ('phone_number', models.CharField(blank=True, help_text="Client's phone number, including country code.", max_length=15, null=True)),
                ('nickname', models.CharField(help_text="Unique identifier for the guest's name.", max_length=255, unique=True)),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('es', 'Spanish'), ('ar', 'Arabic'), ('zh', 'Chinese'), ('tm', 'Tamazight')], default='en', help_text='Preferred language for communication.', max_length=10)),
                ('profile_picture', models.ImageField(blank=True, help_text='Profile picture of the client.', null=True, upload_to='clients/profile_pictures/')),
                ('address', models.TextField(blank=True, help_text="Client's primary address.", null=True)),
                ('profile_completion', models.PositiveIntegerField(default=0, help_text='Tracks percentage of profile completeness (0-100).')),
                ('is_verified', models.BooleanField(default=False, help_text="Indicates if the client's account is verified.")),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'indexes': [models.Index(fields=['user', 'preferred_language'], name='client_clie_user_id_16cabe_idx'), models.Index(fields=['is_verified'], name='client_clie_is_veri_205d81_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_disabled', models.BooleanField(default=False)),
                ('session_key', models.CharField(db_index=True, help_text="The user's session key whose preferences are being tracked.", max_length=100)),
                ('status', models.CharField(choices=[('ACT', 'Active'), ('INA', 'Inactive'), ('SUS', 'Suspended'), ('PEN', 'Pending Verification'), ('BLK', 'Blacklisted')], default='PEN', max_length=3)),
                ('profile_picture', models.URLField(blank=True)),
                ('last_active', models.DateTimeField(blank=True, null=True)),
                ('acquisition_channel', models.CharField(blank=True, max_length=50)),
                ('acquisition_source', models.CharField(blank=True, max_length=100)),
                ('internal_notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Profile',
                'verbose_name_plural': 'Client Profiles',
                'indexes': [models.Index(fields=['status'], name='client_clie_status_361fa1_idx'), models.Index(fields=['last_active'], name='client_clie_last_ac_cf3ac4_idx')],
            },
        ),
        migrations.CreateModel(
            name='GuestIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_disabled', models.BooleanField(default=False)),
                ('session_key', models.CharField(help_text="Unique identifier for the guest's session.", max_length=255, unique=True)),
                ('nickname', models.CharField(help_text="Unique identifier for the guest's name.", max_length=255, unique=True)),
                ('email', models.EmailField(blank=True, help_text='Optional email address provided by the guest.', max_length=254, null=True, unique=True)),
                ('last_active_at', models.DateTimeField(auto_now=True, help_text='Tracks the last time the guest was active.')),
                ('is_converted', models.BooleanField(default=False, help_text='Indicates whether the guest has converted into a registered user.')),
                ('notes', models.TextField(blank=True, help_text='Additional notes or metadata about the guest.', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guest Client',
                'verbose_name_plural': 'Guest Clients',
                'indexes': [models.Index(fields=['session_key'], name='client_gues_session_81c474_idx'), models.Index(fields=['email'], name='client_gues_email_19da95_idx'), models.Index(fields=['is_converted'], name='client_gues_is_conv_78cdda_idx')],
            },
        ),
    ]
