# Generated by Django 6.0.4 on 2026-05-23 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_deactivated_by_client_is_deactivated_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deactivated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deactivated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='guestidentity',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deactivated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shoppinghistory',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deactivated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
